version: '2'
services:
  tests: &base
    build: .
    image: keboola/orchestrator-php-client
    tty: true
    stdin_open: true
    working_dir: /code
    command: composer tests
    environment:
      - ORCHESTRATOR_API_URL
      - ORCHESTRATOR_API_TOKEN
      - ERROR_NOTIFICATION_EMAIL
  dev: &dev
    <<: *base
    volumes:
      - ./:/code
networks:
  default:
    external:
      name: orchestrator-router_api-tests
